### ISSUE TITLE
execvp ldconfig exec format error

### ISSUE THREAD

**Issue by wichtounet** [johnramsden/pathofexile-flatpak#1]
Hi, 

First of all, thanks a lot for this :)

I'm trying to use it on my computer. It seems the installation went fine, but the execution did not go as well: 

```
> flatpak run ca.johnramsden.pathofexile
execvp ldconfig: Exec format error
error: ldconfig failed, exit status 256
```

My guess is simply that this requires 32bit support and my system is installed in full 64bit mode. 

Is that correct ?

Thanks

**Comment by johnramsden** [comment]
That's strange, the flatpak should be able to run the 32 bit application since it should include the runtime necessary. Do you have the 32 bit gnome runtime '`org.gnome.Platform/i386/3.28`' installed?

Could you also try running `strace -o log -f flatpak run ca.johnramsden.pathofexile`? It will write to a file `log`, could you attach the contents?

**Comment by wichtounet** [comment]
In my case, I don't even have 32bit support in my kernel :P

I was hoping that the flatpack would only use the 64bits version of POE. 

I put the log online (https://gist.github.com/wichtounet/bf2e588a652d1e5d00aa8a58cd6969a2), but I don't think it'll help. 

Thanks for the support, but I don't think I can run POE on a pure 64bits linux system.

**Comment by johnramsden** [comment]
@wichtounet I was under the assumption that there shouldn't be a problem running a 32-bit flatpak on a 64-bit host with the [bundled 32-bit runtime](https://github.com/flatpak/flatpak/wiki/Multiarch#bundled-32-bit-runtime). 

Either way, I am trying to get POE working properly using 64bit only, if you want to open a new issue for a 64-bit package I can keep you informed on the progress.

**Comment by wichtounet** [comment]
@johnramsden Sorry, totally forgot this post :(

I would love if it would work on a  64 bit only system. 

Even with a 32-bit runtime bundled, you would still need kernel support for 32bit emulation. 
I don't mind recompiling my kernel, just saying. It's still much better than to install full 32 bits libraries.

**Comment by johnramsden** [comment]
@wichtounet I tried to get a package working last week, and I'm working on it in a separate [branch](https://github.com/johnramsden/pathofexile-flatpak/tree/multiarch-64bit). Unfortunately it's a bit more complicated than I originally thought because even 64-bit wine requires 32-bit libraries for most software meaning I need to do a [WoW64 build](https://wiki.winehq.org/Building_Wine#Shared_WoW64) of wine. I'm not sure what the recommended way is to get a 64bit flatpack with the required multilib libraries at build time is, but I posted a message to the mailing list requesting some help.
